server:
  port: 8081

### Spring Properties
spring:
  application:
    name: pres
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  # SQL Server datasource Properties
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq_test
    username: root
    password: Test#12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA properties
  jpa:
    generate-ddl: true
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 30
        ddl-auto: none
        show_sql: false
        format_sql: false
        order_inserts: true
        order_updates: true
        type:
          preferred_instant_jdbc_type: TIMESTAMP
        envers:
          audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
          global_with_modified_flag: true
  rabbitmq:
    username: pres-user
    password: pres-user
    host: localhost
    port: 15672
    template:
      exchange: pres
      routing-key: rave-ws
