server:
  port: 8081

### Spring Properties
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  # SQL Server datasource Properties
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq_test
    username: root
    password: Test#12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA properties
  jpa:
    generate-ddl: true
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 30
        ddl-auto: update
        type:
          preferred_instant_jdbc_type: TIMESTAMP

  rabbitmq:
    username: pres-user
    password: pres-user
    host: localhost
    port: 5672
    queue: pres-rave-ws
    template:
      exchange: pres
      routing-key: rave-ws

